--CREATE DEFINER=`bb3b063a6a284c`@`%` PROCEDURE `Parameters_Add`(
--in Rz varchar(255),in Ra varchar(255),in Rmax varchar(255),in Sm varchar(255),in S varchar(255),in Image varchar(1000))
--BEGIN 
--insert into Parameters (Rz, Ra, Rmax, Sm, S, Image)
--	values (Rz, Ra, Rmax, Sm, S, Image);
--END
