--CREATE DEFINER=`bb3b063a6a284c`@`%` PROCEDURE `Probe_Add`(
--in name varchar(255), Specifications varchar(1000))
--BEGIN
--insert into probe (Name, Specifications)
--	values (Name, Specifications);
--End
