--CREATE DEFINER=`bb3b063a6a284c`@`%` PROCEDURE `Testingcase_Add`(
--in UserId int(255), SurfaceId int(255), ObjectId int(255), DeviceId int(255), ParametersId int(255), ProbeId int(255), Date datetime(6),Length int(255), Comments varchar(1000), Time_testing time)
--BEGIN
--insert into testingcase (UserID, SurfaceID, ObjectID, DeviceID, ParametersID, ProbeID, Date,Length, Comments, Time_testing)
--	values (UserId, SurfaceId,ObjectId,DeviceId,ParametersId, ProbeId, Date,Length,Comments,Time_testing);
--End
